web: java -cp target/classes:target/dependency/* -Djava.util.logging.config.file=src/test/resources/logging.properties  com.github.brunoabdon.commons.heroku.Main
migrate: java -cp target/classes:target/dependency/* com.github.brunoabdon.gastoso.load.DBMigrate
debug: java -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1806 -cp target/classes:target/dependency/* -Djava.util.logging.config.file=src/test/resources/logging.properties com.github.brunoabdon.commons.heroku.Main 
